# Generated by Django 2.1.5 on 2019-01-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbr_id', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=15)),
                ('mdn', models.CharField(max_length=11)),
                ('birth', models.CharField(max_length=8)),
                ('crdNo', models.CharField(max_length=16)),
                ('last_sales_day', models.DateField(verbose_name='last sales')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbr_id', models.CharField(max_length=9)),
                ('point_kind', models.CharField(max_length=3)),
                ('point_amt', models.IntegerField(default=0)),
                ('upd_dt', models.DateField(verbose_name='update date')),
            ],
        ),
    ]
