# Generated by Django 2.1.5 on 2019-02-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField()),
            ],
            options={
                'db_table': 'OneTwo',
            },
        ),
        migrations.CreateModel(
            name='Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two', models.IntegerField()),
            ],
            options={
                'db_table': 'OneTwo',
            },
        ),
        migrations.RenameField(
            model_name='toy',
            old_name='release_Date',
            new_name='release_date',
        ),
    ]
